name: Entrega continua

on:
  workflow_call:

jobs:

  EC2:
      runs-on: ubuntu-latest
      steps:
      - name: obtendo arquivo da tarefa
        run: aws ecs describe-task-definition --task-definition Tarefa_API-GO --query taskDefinition > task-definition.json
